apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
    - name: test-container
      image: ilayzen/postgres-backup
      command: ["sleep", "3600"]
      volumeMounts:
        - name: pg-volume
          mountPath: /var/lib/postgres/backups
  volumes:
    - name: pg-volume
      persistentVolumeClaim:
        claimName: postgres-backup-pvc